### ISSUE TITLE
[FEAT] Refactor map page

### ISSUE THREAD

**Issue by nami-koko** [coconut-thisABLE/thisABLE_front_2#4]
**Feature description**
- Refactor components used in map page

**Tasks**
TODOs, FIXMEs
- [ ] fix types of postReview props (user.service.tsx)
- [ ] make modalView without bootstrap
- [ ] fix navigator bug
- [ ] fix list type error

**Additional context**
